# This is a basic workflow to help you get started with Actions

name: make template 

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - test-send-to-slack

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.2

      - name: install depedencies
        run: poetry install

      - name: make template
        run:
          poetry run template
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          TOP_PAGE_URL: ${{ secrets.TOP_PAGE_URL }}
